ACTIVE_PROFILE: prod

PRIVATE_KEY:
PUBLIC_KEY:

POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letmein
POSTGRES_DATABASE: localdb
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432

USER_NAME: admin
PASSWORD: letmein

SERVER_PORT: 8080
UI_APP_URL: http://localhost:3000

